name: macOS Arm64 - arm64-osx

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.4"

      - name: Allow pip to break system packages
        run: |
          mkdir -p ~/.config/pip
          echo "[global]" > ~/.config/pip/pip.conf
          echo "break-system-packages = true" >> ~/.config/pip/pip.conf

      - name: Install dependencies
        run: >
          brew install git ninja python3 ruby libxml2 pkg-config &&
          (yes | brew install p7zip) &&
          gem install --no-document fpm

      - name: Clone and bootstrap vcpkg
        run: >
          git clone https://github.com/microsoft/vcpkg.git "$HOME/vcpkg" &&
          cd "$HOME/vcpkg" &&
          chmod +x bootstrap-vcpkg.sh &&
          ./bootstrap-vcpkg.sh &&
          cd -

      - name: Build Alusus
        run: ALUSUS_VCPKG_REPO_PATH="$HOME/vcpkg" ./Tools/build.sh --build-type release --clean-and-build --target-triplet arm64-osx --build-packages

      - name: Automated tests Alusus
        run: |
          bash -c "cd ./AlususBuild/Intermediate/arm64-osx-release && ctest --output-on-failure"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: AlususBuild/Packages
          retention-days: 5
